version: '3'
services:
  duckdns:
    container_name: duckdns
    restart: unless-stopped
    image: linuxserver/duckdns
    env_file: /opt/duckdns/duckdns.env
#    labels:
#      - com.centurylinklabs.watchtower.enable="false"
