version: '3'
services:
  kodi:
    container_name: kodi
    restart: unless-stopped
    image: linuxserver/kodi-headless:Krypton
    volumes:
      - /opt/kodi/.kodi:/config/.kodi
    environment:
      - PGID=1006
      - PUID=1000
      - TZ=Europe/Stockholm
    ports:
      - 8082:8082
      - 9777:9777/udp
      - 9090:9090
networks:
  default:
    external:
      name: br0
