version: '3'
services:
  muximux:
    container_name: muximux
    image: linuxserver/muximux
    restart: always
    ports:
      - 8883:80
    volumes:
      - /opt/muximux:/config
    environment:
      - PUID=1000
      - PGID=1006
      - TZ=Europe/Stockholm
