version: '2'
services:
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    environment:
     - 'management 0.0.0.0 5555'
    restart: always
    volumes:
     - /opt/ovpn:/etc/openvpn

  monitor:
    image: ruimarinho/openvpn-monitor
    container_name: ovpnmonitor
    ports:
      - "8084:80"
    restart: always
    depends_on:
      - openvpn
    env_file: /opt/ovpn/monitor.env
