version: '3'
services:
  emby:
    container_name: emby
    image: emby/embyserver
    restart: always
    ports:
      - 8096:8096
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/emby:/config
      - /media/4tb:/media
    environment:
#      - VIRTUAL_PORT=8096
#      - VIRTUAL_HOST=emby.docker
      - APP_UID=1000
      - APP_GID=1006
