version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    ports:
      - 8123:8123
#    network_mode: host
    environment:
      - TZ=Europe/Stockholm
    labels:
      - com.centurylinklabs.watchtower.enable="false"
