version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:latest
    volumes:
      - /opt/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /media/8tb:/media/8tb:ro
      - /media/timemachine:/media/timemachine:ro
      - /media/backup4tb:/media/backup4tb:ro
      - /media/4tb:/media/4tb:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
#    ports:
#      - 8123:8123
    network_mode: host
    environment:
      - TZ=Europe/Stockholm
    # labels:
    #   - com.centurylinklabs.watchtower.enable=false
networks:
  default:
    external:
      name: br0
