version: '3'
services:
  pihole:
    container_name: pihole
    restart: unless-stopped
    image: pihole/pihole:latest
    volumes:
      - /opt/pihole:/etc/pihole
      - /opt/pihole/pihole.log:/var/log/pihole.log
      - /opt/pihole/hosts:/etc/hosts
#      - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d
    env_file: /opt/pihole/pihole.env
#     environment:
#       - ServerIP=192.168.1.21
#       - TZ=Europe/Stockholm
#       - DNS1=192.168.1.1
#       - DNS2=8.8.8.8
#       - WEBPASSWORD='YX-ScRwL'
# #      - VIRTUAL_HOST=proliant.home
# #      - IPv6=False
    dns:
      - 127.0.0.1
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
    networks:
      static_network:
        ipv4_address: 172.18.0.4

networks:
  static_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16
