mqtt:
  image: eclipse-mosquitto:latest
  container_name: mosquitto
  restart: always
  ports:
    - "1883:1883"
    - "9001:9001"
  volumes:
    - /opt/mosquitto/config:/mosquitto/config
    - /opt/mosquitto/data:/mosquitto/data
    - /opt/mosquitto/log:/mosquitto/log
