version:  '3'
services:
  grafana:
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    volumes:
      - /opt/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=<user>
      - GF_SECURITY_ADMIN_PASSWORD=<password>
    network_mode: host
    user: "1000"
