version: '3'
services:
  couchpotato:
    container_name: couchpotato
    image: linuxserver/couchpotato
    restart: always
    ports:
      - 5050:5050
    volumes:
      - /opt/couchpotato:/config
      - /media/downloads:/downloads
      - /media/movies:/movies
    environment:
      - PGID=1006
      - PUID=1000
      - TZ=Europe/Stockholm
      - UMASK_SET=<022>
    
