version: "3"
services:
  watchtower:
    restart: unless-stopped
    container_name: watchtower
    image: watchtower:local
#    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 600 
    command: --schedule @midnight --cleanup
    env_file: /opt/watchtower/settings.env
    labels:
      - com.centurylinklabs.watchtower.enable=false
