version: "3"
services:
  watchtower:
    restart: always
    container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#    command: --interval 300 
    command: --schedule @midnight --cleanup --debug
    env_file: /opt/watchtower/settings.env
