version: "3"
services:
  watchtower:
    restart: always
    container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /opt/watchtower/config.json:/config.json
    command: --interval 30
