version: '3'
services:
    jackett:
        image: linuxserver/jackett
        container_name: jackett
        restart: always
        ports:
            - 9117:9117
        volumes:
            - /media/downloads:/downloads
            - /opt/jackett:/config
        environment:
            - PUID=1000
            - PGID= 1006
            - TZ=Europe/Stockholm

