version: '2'
services:
 transmission:
  container_name: transmission
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /media/4tb/downloads/downloads:/data
  env_file: /opt/vpn-torrent/vpn.env
  
#  environment:
    # - OPENVPN_PROVIDER=PIA
    # - OPENVPN_USERNAME=p6653510
    # - OPENVPN_PASSWORD=JLgEton5p5
    # - OPENVPN_CONFIG=Netherlands
    # - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    # - LOCAL_NETWORK=192.168.1.0/24
    # - TRANSMISSION_WEB_UI=kettu
    # - PUID=1000
    # - PGID=1006
    # - TZ=Europe/Stockholm

 proxy:
  container_name: vpn-proxy
  image: haugene/transmission-openvpn-proxy
  links:
    - transmission
  ports:
    - 8081:8080
  volumes:
    - /etc/localtime:/etc/localtime:ro
  environment:
    - PUID=1000
    - PGID=1006
    - TZ=Europe/Stockholm
