version: "2"
services:
  portainer:
    restart: always
    container_name: portainer
    image: portainer/portainer
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9000:9000
networks:
  default:
    external:
      name: br0
