version: '3'
services:
  netdata:
    image: titpetric/netdata:latest
    container_name: netdata
    hostname: proliant.local
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - /opt/netdata/netdata.env
