# This file is deprecated
# Please refer to the compose file of Influxdb for details

version: '3'
services:
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - influxdb_network

networks:
  influxdb_network:
    external: true
