version: '3'
services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb:latest
    volumes:
      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/influxdb/db:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file: /opt/influxdb/influxdb.env
    ports:
      - "8086:8086"
    labels:
      - com.centurylinklabs.watchtower.enable=false


  telegraf:
    container_name: telegraf
    image: telegraf
    depends_on:
      - influxdb
    volumes:
      - /opt/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
networks:
  default:
    external:
      name: br0
