version: '3' 
services:
  influxdb:
    container_name: influxdb
    restart: unless-stopped
    image: influxdb:1.5.2
    volumes:
      - /opt/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /opt/influxdb/db:/var/lib/influxdb
    env_file: /opt/influxdb/influxdb.env
#    environment:
#      - INFLUX_ADMIN_USER=myggan - 
#      INFLUX_ADMIN_PASSWORD=hubert
    ports:
      - "8086:8086"
    networks:
      - influx_net

networks:
  influx_net:
    driver: bridge
